In [1]:
import pandas as pd
store = pd.read_csv("store_rev.csv", index_col = 0)
store.head()

      revenue  reach  local_tv  online  instore  person       event
845  45860.28      2  31694.91    2115     3296       8   non_event
483  63588.23      2  35040.17    1826     2501      14     special
513  23272.69      4  30992.82    1851     2524       6     special
599  45911.23      2  29417.78    2437     3049      12     special
120  36644.23      2  35611.11    1122     1142      13  cobranding

In [2]:
store.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 985 entries, 845 to 26
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   revenue   985 non-null    float64
 1   reach     985 non-null    int64
 2   local_tv  929 non-null    float64
 3   online    985 non-null    int64
 4   instore   985 non-null    int64
 5   person    985 non-null    int64
 6   event     985 non-null    object
dtypes: float64(2), int64(4), object(1)
memory usage: 61.6+ KB

In [3]:
store.isnull().sum()

revenue      0
reach        0
local_tv    56
online       0
instore      0
person       0
event        0
dtype: int64

In [4]:
store.describe()

,revenue,reach,local_tv,online,instore,person
count,985.000000,985.000000,929.000000,985.000000,985.000000,985.000000
mean,38357.355025,3.395939,31324.061109,1596.527919,3350.962437,11.053807
std,11675.603883,1.011913,3970.934733,496.131586,976.546381,3.041740
min,5000.000000,0.000000,20000.000000,0.000000,0.000000,0.000000
25%,30223.600000,3.000000,28733.830000,1253.000000,2690.000000,9.000000
50%,38159.110000,3.000000,31104.520000,1607.000000,3351.000000,11.000000
75%,45826.520000,4.000000,33972.410000,1921.000000,4011.000000,13.000000
max,79342.070000,7.000000,43676.900000,3280.000000,6489.000000,24.000000

In [5]:
store["event"].unique()

array(['non_event', 'special', 'cobranding', 'holiday'], dtype=object)

In [6]:
store.groupby("event")["revenue"].describe()

,count,mean,std,min,25%,50%,75%,max
event,,,,,,,,
cobranding,398.0,38277.664497,11879.097324,7146.99,30472.1525,37864.155,46333.5600,79342.07
holiday,103.0,37791.890583,11942.369136,5000.00,29644.5250,38432.780,46036.1300,73377.15
non_event,192.0,37903.081562,11186.436740,6874.43,29852.3775,37937.175,44611.6375,69429.39
special,292.0,38964.136438,11648.616882,10207.96,30325.8125,39197.870,45897.0400,71757.50

In [7]:
store.groupby("event")["local_tv"].describe()

,count,mean,std,min,25%,50%,75%,max
event,,,,,,,,
cobranding,376.0,31424.590186,3951.049566,21252.35,28746.9725,31336.570,33839.0200,42162.64
holiday,96.0,30860.524896,4448.719364,21792.84,27769.6000,30564.705,33595.5975,41047.01
non_event,182.0,31415.197527,3952.155383,20000.00,29222.5875,31238.235,34386.0825,42069.84
special,275.0,31288.110982,3842.412128,21428.20,28668.7100,30921.790,34105.6250,43676.90

In [8]:
store.corr()

           revenue     reach  local_tv    online   instore    person
revenue   1.000000 -0.155314  0.602114  0.171227  0.311739  0.559208
reach    -0.155314  1.000000 -0.034039 -0.025141  0.035635  0.061417
local_tv  0.602114 -0.034039  1.000000  0.006775 -0.046825  0.048664
online    0.171227 -0.025141  0.006775  1.000000 -0.026399  0.036662
instore   0.311739  0.035635 -0.046825 -0.026399  1.000000 -0.007482
person    0.559208  0.061417  0.048664  0.036662 -0.007482  1.000000

In [9]:
store.corr()[["revenue"]].sort_values(by = "revenue", ascending = False)

           revenue
revenue   1.000000
local_tv  0.602114
person    0.559208
instore   0.311739
online    0.171227
reach    -0.155314

In [10]:
store.dropna(inplace = True)

In [11]:
store.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 929 entries, 845 to 26
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   revenue   929 non-null    float64
 1   reach     929 non-null    int64
 2   local_tv  929 non-null    float64
 3   online    929 non-null    int64
 4   instore   929 non-null    int64
 5   person    929 non-null    int64
 6   event     929 non-null    object
dtypes: float64(2), int64(4), object(1)
memory usage: 58.1+ KB

In [12]:
y = store["revenue"]
x = store[["local_tv", "person", "instore"]]

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
transfer = MinMaxScaler()

In [15]:
x1 = transfer.fit_transform(x)

In [16]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x1, y)

LinearRegression()

In [17]:
y_predict = model.predict(x1)

In [18]:
y_predict

array([32585.64184447, 47431.83291658, 24132.8558106 , 35740.64708612,
       40853.97183715, 28825.79830374, 40498.9221121 , 45517.30052323,
       14063.48401264, 24838.03635187, 33806.09701815, 28380.46336884,
       28200.83400364, 44021.13365515, 27854.49730469, 25046.51761115,
       51772.01264013, 37177.92826862, 36914.72691029, 38069.18624192,
       17551.30368111, 24458.69894588, 48346.1575792 , 40321.32585109,
       52749.32938638, 31834.15091164, 33914.42552398, 52650.38777457,
       43503.67228251, 31747.97008329, 52075.11168805, 20296.27644815,
       29146.75504732, 50193.99310135, 45561.51988805, 23544.20036175,
       53080.00037957, 32760.98608532, 31701.12259263, 48458.98900029,
       59500.09321151, 42552.9446609 , 34846.59363043, 26972.53467258,
       27069.08585651, 41653.00404349, 36998.41570891, 31135.74543132,
       39238.20048722, 33002.77164774, 15613.8860636 , 35462.43208725,
       45657.27862352, 26018.43029962, 21361.92556513, 26969.99854228,
       41140.93665304, 50206.33820597, 46803.51625653, 31816.13097594,
       34775.55094279, 15196.98546407, 39639.23865375, 38351.46670533,
       37502.03311318, 30706.54262559, 32153.3856997 , 25310.30672262,
       34752.22923997, 30449.20837602, 52387.56443953, 43095.61794126,
       29629.73861817, 45001.60210018, 47754.68460965, 33849.79028338,
       41583.03994519, 30692.85121916, 35504.37821817, 17946.6596409 ,
       33256.68836162, 49121.77157002, 24318.02989514, 27646.12492123,
       37964.25396042, 33648.81891449, 45357.54027649, 18993.48929863,
       40559.94919643, 39133.35028593, 56806.55984639, 43607.5314539 ,
       48805.0731268 , 44177.97220172, 30859.07845986, 34188.10138564,
       46355.22839025, 24671.73003955, 36150.09855839, 44232.76735072,
       33416.89162709, 32813.52246223, 35938.39178255, 38884.26044917,
       45190.01703248, 45634.65325792, 47781.20709354, 43304.18160378,
       27767.523132  , 35748.71651609, 17326.40004485, 35031.0639706 ,
       54994.63492059, 29476.80791479, 43874.09684342, 40397.11847547,
       22978.55939199, 19601.43603356, 35785.69322046, 34294.52127713,
       28722.84880785, 57908.1158246 , 48512.53362914, 30296.27549391,
       36512.65611501, 37899.0856067 , 34079.06373134, 45612.0189687 ,
       20364.62023701, 25056.57173977, 42274.96249348, 30038.11290986,
       34866.82382575, 48782.73503734, 38185.28153933, 48679.5790407 ,
       39331.59444698, 53553.6523617 , 33025.17436618, 41483.83893157,
       33731.78545219, 35911.55393436, 46506.49535875, 42852.51624496,
       28468.94651858, 26475.95135395, 26901.9150984 , 38737.62193889,
       39396.6077746 , 33024.99196366, 37570.66156926, 35706.53157109,
       32409.31432209, 42114.9009504 , 36238.97025227, 28803.09828107,
       29260.65044956, 24042.48751577, 57413.47650602, 31944.10419124,
       36675.20799175, 30980.91508587, 27779.33872858, 61230.99909347,
       29705.82521032, 56412.53639235, 15549.47650459, 40779.03784565,
       39769.3650771 , 23703.18250365, 45015.12266969, 43285.78118862,
       39297.82948392, 42267.7724591 , 52390.88163844, 23990.97207118,
       29447.07280948, 26807.51602759, 56830.30235139, 30888.94676794,
       45096.27647061, 28199.3399685 , 31183.15073572, 35009.84689961,
       29661.40587379, 43996.52356849, 24954.14450494, 27725.39124426,
       37555.10682325, 16980.873406  , 45384.88108677, 36032.09455818,
       41094.73986626, 41128.06579909, 52693.01762577, 44974.96289023,
       38520.85358483, 33156.23058679, 48674.28075441, 44582.63152017,
       36853.56835631, 39738.73681803, 39943.00094435, 34188.79664834,
       39628.50499461, 34534.04543019, 49490.30120983, 31151.71610566,
       47615.19192911, 28917.99909165, 49613.76054713, 20359.59886847,
       45102.87881413, 47444.30093774, 57732.34066584, 28566.63791452,
       23177.02194851, 30115.92888139, 46522.56258213, 38971.43774987,
       35963.74332279, 37290.00210686, 55809.25002144, 41739.68996173,
        8910.38767519, 34050.89173719, 40338.13350393, 39319.77061334,
       46261.87113516, 41742.27164255, 41226.11527011, 49785.35579376,
       42080.08162815, 28180.13056777, 36293.14271394, 37876.71339986,
       38244.57925   , 29725.51104183, 72063.80872182, 39754.75045019,
       29489.01161778, 41454.06965519, 51438.34400662, 28395.63625043,
       44301.65020182, 45721.85131474, 42571.02509396, 29303.90744294,
       38524.03288051, 35786.96360679, 43061.86942233, 39054.56778647,
       64276.0096899 , 52557.81807359, 39920.62958084, 29086.47483786,
       48316.46698279, 45763.60601811, 16924.12195101, 23560.24281272,
       36833.09153215, 36284.52138738, 29063.7843747 , 40328.58029068,
       63486.50496493, 47871.43239538, 52078.82451728, 22328.92889212,
       40562.97006468, 34804.97943148, 29427.689063  , 43146.65410732,
       55997.17991172, 37411.56847305, 38536.76533005, 25092.75462131,
       36223.41564815, 32693.86737581, 35947.04361407, 56529.10499481,
       47645.05925196, 40544.3941701 , 32807.80288351, 40080.7490722 ,
       66867.04825438, 33177.26375464, 28709.96089177, 43119.62398692,
       20842.33758997, 36956.5579184 , 52215.47509042, 48338.80675161,
       35520.45781742, 35188.43614072, 43801.52955925, 44569.28600674,
       39539.20890482, 36120.85807056, 25731.68118931, 38735.31387591,
       18300.1161051 , 32062.22020199, 38900.60561533, 44374.97436361,
       21291.88295337, 49563.40787628, 34017.60940241, 40028.49258564,
       35444.3551235 , 25564.38134229, 44280.36078826, 40473.5389615 ,
       40645.12481406, 54275.55089068, 36282.00874325, 10500.11437278,
       38061.68030205, 40888.67370933, 54525.71575942, 17565.93191107,
       23194.82883919, 22176.51840326, 31023.44941499, 24281.49937673,
       33413.97390516, 45231.94131062, 58488.76304555, 50517.39702915,
       52707.10614604, 47936.01524604, 35405.77454907, 40666.44526698,
       32344.40224538, 52097.37878826, 57771.29864533, 42439.06104462,
       53896.47239191, 37594.46504643, 34893.72841282, 28058.28870657,
       47900.23116337, 42361.29358579, 38761.83758857, 29008.95073781,
       15762.46319009, 45546.25729363, 39427.14183105, 31177.38265312,
       31038.10226294, 44611.86213805, 21669.57453452, 47216.27287287,
       36894.86104297, 33793.18315198, 46013.51728233, 49170.82971764,
       36274.30339973, 32594.5598924 , 46413.82250641, 69620.8391079 ,
       36449.30598446, 36744.21100151, 17825.47098905, 37349.15184855,
       49578.55177688, 27721.05193112, 32718.2059447 , 35515.22262528,
       50698.92891573, 50464.35453052, 32122.90640383, 26082.12883019,
       48463.20802777, 16324.32853697, 42500.44986855, 22381.226934  ,
       41528.95999978, 71979.64277676, 36329.11271087, 43225.16481879,
       49804.8621575 , 29447.03329368, 54209.86374374, 40152.34737487,
       44876.48715961, 51057.6781435 , 40692.14596195, 37412.69214158,
       32348.94125936, 28061.70452358, 45923.34928769, 33976.17192264,
       29960.76656237, 31137.55667752, 37403.22343198, 35710.0583716 ,
       39011.81090476, 33986.56932064, 39343.04131007, 25380.70151313,
       44069.91236742, 28655.14028482, 35750.95771061, 43078.16317386,
       41971.18674172, 38408.05587917, 48639.10612348, 48423.57972103,
       29572.47860616, 42223.27377554, 57084.98274068, 31280.52326967,
       18582.48218275, 40093.59531288, 36014.25101424, 40893.85074963,
       40247.79955263, 38970.52220888, 41308.21078759, 59718.91396229,
       28193.89057589, 52411.67792917, 40229.69037289, 33690.91665034,
       36413.85391551, 48803.24716447, 46055.27240108, 40025.9519112 ,
       31494.61294989, 35749.64110522, 43624.84132653, 40407.76187638,
       31653.04230048, 45109.48526024, 35550.27808119, 64456.14158268,
       34413.59951922, 36487.85641036, 47010.66017576, 43602.61378279,
       28004.58133366, 43401.203954  , 55842.38049724, 39755.05298873,
       40407.44173148, 36375.14550816, 26748.401916  , 38528.76641587,
       38054.16738754, 29284.1936777 , 31044.71074129, 39818.19619583,
       54089.7913469 , 49833.4983533 , 32582.07135546, 45554.01751676,
       32735.33594607, 51389.58314059, 36838.99816176, 26483.92177074,
       46515.50416481, 51639.69025614, 27386.05239879, 23050.17616744,
       53563.39915426, 28574.02531017, 39053.60163124, 41875.89342459,
       19535.13353927, 49888.90657015, 46156.20703809, 33238.81248815,
       40032.38439575, 44761.8001568 , 47848.9630395 , 48319.72900137,
       61391.88727895, 36912.31449823, 41120.87393468, 25801.45301194,
       42590.11073622, 47960.53265582, 33878.09901317, 23481.49229457,
       33828.16531491, 36892.2066947 , 39271.34748321, 45355.44117132,
       33152.6279702 , 32655.73011891, 39308.1375884 , 50275.97388784,
       38537.98627715, 55841.8831038 , 33712.32075326, 49333.5624348 ,
       23861.77494302, 49123.42149677, 33380.35695361, 42793.49432976,
       16694.73851659, 49446.62169109, 17433.49500308, 42674.93118337,
       28023.25778435, 55125.51742124, 39881.40980984, 49893.613287  ,
       42996.32099834, 34261.18581073, 39965.30355746, 44396.57242671,
       56219.58433617, 40334.55517016, 36324.0962719 , 30624.43747554,
       37972.22370437, 53103.21284328, 23208.09048212, 43368.01442262,
       38814.62915537, 38352.57567466, 29152.46785868, 30317.32492425,
       51738.99658865, 37005.10513948, 35649.83330979, 47687.38513212,
       17033.05902457, 47742.8079104 , 44704.03186348, 19402.97939384,
       53419.9935326 , 37929.8517336 , 40104.24952029, 50162.17960012,
       37494.52702437, 32181.189871  , 62154.28971698, 45637.09762357,
       42977.40799451, 54965.14557942, 37213.9462769 , 28198.92165327,
       41238.34938963,  4411.44793985, 41494.72591303, 47146.85902936,
       37395.80438859, 38875.77752728, 54901.81152556, 34880.96235085,
       34271.83558292, 54913.99447426, 11736.831355  , 45134.49819201,
       42023.54616894, 22053.69641662, 45873.03421849, 37142.7422189 ,
       32392.3167613 , 19565.55643834, 29451.45529449, 43134.59039217,
       45104.56886122, 17012.44663238, 41081.39326004, 49924.25518085,
       33783.81338017, 39511.69464603, 62477.79640982, 31436.73266645,
       32498.54330694, 36179.24324627, 27053.55846846, 39994.15277843,
       47976.70011963, 28677.28144664, 36152.74406419, 35038.01434152,
       24053.88636146, 30816.49222262, 49895.97816897, 53645.76085454,
       33123.99376947, 38823.45566766, 22694.97115584, 20835.21738997,
       33817.25924308, 45971.80497973, 26636.66330757, 38663.22590754,
       36724.62693264, 49949.82699832, 38735.22895028, 50332.79664783,
       57400.25048203, 21718.1122496 , 27794.79503764, 40889.84521839,
       37400.0489992 , 36079.4856701 , 17822.39378119, 47509.81553493,
       49494.41618851, 26748.41066917, 39407.38065914, 37712.1453974 ,
       46229.18802711, 22819.11843455, 52909.08167687, 54258.35093234,
       40884.74748022, 42254.44873979, 35728.61410919, 57813.44168474,
       33815.99778858, 46404.562002  , 36328.37872728, 35070.49011302,
       56601.00311834, 28566.64082766, 25425.36707278, 42292.00779058,
       28944.88422244, 26314.45011871, 30548.49865653, 37276.10361774,
       42603.74989221, 36699.660691  , 36242.25043147, 20585.98483854,
       37662.05659607, 47602.18721068, 29969.526237  , 50541.92272874,
       43033.97590206, 31724.66981725, 36090.02168461, 25499.81517199,
       46815.41253388, 40940.02164688, 22767.71093907, 34595.75936066,
       39820.09348468, 32609.705334  , 38453.49383171, 39003.03253755,
       39143.67997768, 22397.79762108, 48725.24097676, 34655.326129  ,
       42383.00790058, 47231.0313781 , 37621.1944049 , 32648.68578387,
       38336.70482622, 48491.64575917, 22257.51234053, 65119.39725067,
       32846.14378721, 29539.06841583, 34165.58821061, 41067.00013537,
       33852.65787929, 38568.09953691, 34268.53297977, 29720.43158879,
       50914.67883746, 40497.66632598, 27366.1348548 , 20435.09915805,
       32238.04039174, 31324.42960299, 49581.36237359, 43472.21643941,
       55553.33559767, 35061.0122637 , 35627.20113174, 71028.921658  ,
       42373.48252645, 28489.92096337, 52022.57593396, 40552.90909482,
       27699.76576032, 25110.89555507, 38624.86596871, 36970.44941204,
       44711.23751691, 49349.17711274, 30365.53109323, 53394.63904179,
       47880.5036085 , 52388.93451194, 30978.97354947, 38151.30676657,
       32941.7238322 , 40223.07949511, 36065.16164613, 30808.82779347,
       32578.88659074, 46893.31713367, 46643.500586  , 47149.82223466,
       24723.31077843, 36882.67442586, 38829.29014305, 35915.79163268,
       25001.01723969, 44803.614098  , 48760.67797128, 36561.17878727,
       32657.78626311, 36553.16052307, 50519.03141867, 39834.82663779,
       45883.08917127, 31499.50022688, 40612.30840933, 33827.73136966,
       54056.07822777, 37850.9880016 , 44669.2179781 , 38889.2852622 ,
       40054.294508  , 22332.13058913, 37095.10137669, 51939.62433812,
       45742.83200741, 48194.64037483, 27816.14371163, 28340.48126273,
       28204.12128414, 40862.81580493, 41876.23467648, 29508.86094339,
       41620.02718706, 39971.30261951, 32871.97856735, 36383.46167496,
       45298.88462563, 29040.26838749, 50418.75307705, 30449.12430582,
       39070.78663652, 52050.01244037, 42456.35263388, 39112.14391101,
       37265.54709244, 42214.37628061, 34831.65351343, 46070.26738292,
       36818.49376603, 44456.39314341, 60302.11089889, 27007.94475336,
       31003.46985403, 42249.33216471, 54219.64292434, 46973.67558768,
       40925.82242002, 36020.97541098, 50644.96144576, 47383.61422657,
       29889.47282366, 29887.67078229, 44264.86665073, 37884.6156552 ,
       44873.90352186, 52138.7247502 , 42873.01973112, 35472.19616559,
       35560.49459147, 41066.46679652, 38258.44506571, 41459.25163194,
       44614.74709656, 52084.32855059, 28881.20234629, 43226.21272226,
       33937.66020332, 40229.54681493, 49867.44397258, 36829.27301042,
       27412.61815691, 39821.45832706, 72053.41772062, 46282.69754635,
       36821.9236252 , 29949.58265047, 52287.42874151, 44792.5232722 ,
       51041.65975421, 35485.64043607, 50890.32949774, 49422.26379515,
       33484.07516638, 39019.30482106, 34885.84494225, 35675.39133513,
       26461.40900007, 49973.61543839, 30434.11890203, 18303.110196  ,
       40340.77045966, 62435.78017911, 37019.52920545, 28991.41349567,
        6034.93565234, 40728.54583131, 28900.26804562, 54442.55653851,
       35496.70468124,  9327.39060087, 46105.21040453, 43512.58455408,
       44635.94066973, 32028.16455511, 47158.10829425, 30438.90873756,
       27965.39676555, 45625.99480121, 43893.432854  , 37571.92149643,
       25236.42806348, 36146.15343252, 34374.40211081, 25782.57872012,
       40884.29638991, 29076.44553378, 53905.36893245, 50941.68408757,
       37827.77555481, 48994.60838435, 41715.06512422, 49305.91758487,
       40808.59135833, 34789.97279963, 36422.49248541, 66931.21873425,
       34225.76188933, 27559.45839943, 47694.22267184, 45661.79057   ,
       38142.13199703, 42515.81142706, 38204.30483988, 61333.97451789,
       40884.16937106, 18695.54967716, 37288.69380033, 24317.1905616 ,
       46615.56197645, 19755.98464455, 41784.27911149, 46941.49831044,
       47131.94568468, 44361.04563067, 32418.45134761, 10494.4191502 ,
       37626.90718813, 47950.99699068, 34593.88112831, 46473.70124731,
       36322.54554756, 36848.77428241, 35981.72208056, 40817.14829202,
       27858.67630752, 27689.2881698 , 31866.98898638, 38022.84075306,
       27194.39540228, 38228.14803986, 20507.41992115, 53423.0665838 ,
       30726.33101398, 43530.0884326 , 31986.76873883, 27874.97150896,
       22585.58852196, 38848.12273505, 34973.50833372, 33197.03843016,
       19296.84861228, 47163.51339865, 41377.70073432, 41275.2117562 ,
       44215.47784828, 48058.76491257, 34935.48912623, 39497.05438474,
       36461.42524231, 38731.48734729, 44835.11686134, 59559.45297593,
       46151.78170038, 40929.59434363, 50330.85633316, 32974.63221923,
       47851.22696187, 41443.78729335, 41844.01235482, 36308.07041811,
       37579.33119882, 24129.83095379, 54418.28878841, 45238.32474739,
       46843.11378238, 55832.96613656, 36868.00566386, 33999.63455116,
       42640.33179992, 22038.68205137, 52475.41376487, 32722.7851024 ,
       39096.57624173, 54856.23988499, 58496.77439652, 37519.19733975,
       30940.88803918, 37298.29010186, 46467.40949448, 43822.63318127,
       38716.25772374, 56390.16463788, 36700.23651727, 47952.1201303 ,
       39854.90688668])

In [19]:
model.coef_

array([41478.6429907 , 48907.03909284, 26453.89791677])

In [20]:
model.intercept_

-17641.464384357016